### ISSUE TITLE
Icon-window improvements

### ISSUE THREAD

**Issue by KiwiKaiser** [CaptureCoop/SnipSniper#100]
1. Create own tab for custom icons 
2. Allow drag and drop for custom Icons
3. Cache taskbar icons scales down using anti-aliasing (Custom 16x16, SnSn-own icons 64x64)
4. Show custom icons using anti-aliasing
![grafik](https://user-images.githubusercontent.com/59627902/135901263-247c7a80-6900-4bf4-82fd-a6a1e70f4ffa.png)

**Comment by SvenWollinger** [comment]
1. is done. (Tabs)

**Comment by SvenWollinger** [comment]
2. Is done (Dragging)

**Comment by SvenWollinger** [comment]
4. Is done for the preview buttons

**Comment by SvenWollinger** [comment]
3. Is done (Smooth scaling)

This should be it. Feel free to reopen/create a new issue if something is wrong.
