### ISSUE TITLE
Directly open a plain full size image when opening the editor via the tray-icon

### ISSUE THREAD

**Issue by KiwiKaiser** [CaptureCoop/SnipSniper#130]
Directly open a plain full size image when opening the editor via right click on the tray-icon.

**Comment by SvenWollinger** [comment]
Done :^).

The editor now opens a new empty white image sized by width / 2 and height / 2.

The old behaviour can still be used though, by this config option in file:

![grafik](https://user-images.githubusercontent.com/51021531/147666752-03c97a39-f9b9-4873-ba0a-51c57040dcdf.png)

There is no config window option for this just yet. Would we want this @KiwiKaiser ?
